version: '3.8'
volumes:
  postgre-vol:
networks:
  kubenews_net:
    driver: bridge

services:
  postgre:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - kubenews_net
    volumes:
      - postgre-vol:/var/lib/postgresql/data 
    environment:
      POSTGRES_PASSWORD: Pg123
      POSTGRES_USER: kubenews
      POSTGRES_DB: kubenews

  web:
    image: and3rson/kubnews:v1
    ports:
      - 8081:8080
    networks:
      - kubenews_net
    depends_on: 
      - postgre
    environment:
      DB_DATABASE: kubenews
      DB_USERNAME: kubenews
      DB_PASSWORD: Pg123
      DB_HOST: postgre
      



    

  
  